= Grammatica de Interlingue
:author: Dr. Fritz Haas
:revnumber: 0.1.0-pre.2+20190307
:description: Grammatica de Interlingue in Interlingue
:lang: ie
:docinfo: private
ifdef::backend-pdf[]
:doctype: book
:toc: macro
:toclevels: 3
:toc-title: Contenete
endif::[]

// This Asciidoctor version by Marcos Cruz (programandala.net) for
// http://ne.alinome.net, 2019.

// Last modified 201903070025

:dot: .

// Pri ti libre {{{1
== Pri ti libre

Titul:: Grammatica de Interlingue

Autor:: Dr. Fritz Haas.

Edition original:: Interlingue-Servicie Winterthur, Svissia, 1956.

Digitalisation:: S. Belitzky.

Adaptation a HTML 4.01:: Sebastian Hartwig, 2009. Obtenibil in
http://interlingue.narod.ru[interlingue.narod.ru] e
http://ie-munde.com[ie-munde.com].

Conversion a Asciidoctor, e edition quam libre digital:: Marcos Cruz,
2019{dot} Obtenibil in http://ne.alinome.net[ne.alinome.net] ye
formates EPUB, PDF e altris.

Version de ti edition:: {revnumber}.

// Anteparol {{{1
== Anteparol

Ti grammatica es complet in li sens, que it contene omni essential
regules usat in li textus de Cosmoglotta, li oficial organ del
Interlingue-Union, e in li _Complet Cursu de Interlingue_ de A. Matejka.
In plu omni decisiones del Interlingue-Academie es egardat.

// XXX FIXED -- usar Idiotismes -> usar idiotismes

In contrast a omni lingues national, on posse dir de Interlingue: Qui
aplica li regules de ti grammatica e usa li adequat paroles, parla e
scri Interlingue corectmen. Il ne deve timer audir: Yes, on ne trova un
erra grammatical in vor lettre, ma null anglese vell expresser su pensas
per ti paroles o per ti frase-constructiones! E to constitue li grand
facilitá de Interlingue: Chascun nation posse expresser su pensas in li
cadre del poc regules grammatical in li maniere acustomat, e deve solmen
far atention, ne usar idiotismes íncomprensibil al altri nationes per
usar cert paroles in un altri sens quam li general. Ma li regules
grammatical es tre simplic e sin exceptiones, talmen que on posse
realmen mastrisar les in extrem curt témpor. In plu un grand parte del
regules confirma solmen, que li ja conosset regules del lingue matrin
vale anc in Interlingue.

On posse dunc dir sin exageration, que Interlingue es mult plu facil
quam li precedent projectes de lingue international e íncomparabilmen
plu simplic quam omni lingues national, mem in simplificat form. To vale
ne solmen por li comprension, ma anc por li aprensíon e specialmen anc
por li aplication del lingue.

Winterthur (Svissia), octobre 1956.

Dr. phil. Fritz Haas

Li nómine *Occidental* del lingue international creat de *Edgar von
Wahl* esset 1949 viceat per li nómine *Interlingue*, sin changear li
lingue self, por evitar li politic aspecte del nómine
“Occidental-Union”.

// Alfabet {{{1
== Alfabet

[[par1,§1]]§1. Interlingue es scrit per 26 *lítteres latin: a, b, c, d, e, f, g,
h, i, j, k, I, m, n, o, p, q, r, s, t, u, v, w, x, y, z*.

[[par2,§2]]§2. Li alfabet es *pronunciat*:

a, be, ce, de, e, ef, ge, ha, i, jot, ka, el, em, en, o, pe, qu, er, es,
te, u, ve, duplic ve, ix, ypsilon, zet.

// Pronunciation {{{1
== Pronunciation

[[par3,§3]]§3. *Li vocales* es sempre clarmen pronunciat quam seque:

*a* quam in F (francesi), o G (german), o H (hispan), o I (italian), o A
(anglesi): father. *vase, batte, batter*.

*e* apert o cludet, quam GHI, A: bed, yes, F: é o è. *pena, mensu,
pelle, venir*.

*i* quam FGHI, A: machine. *nive, six, minute*.

*o* apert o cludet, quam FGHI, A: door, hot. *modic, póndere, porta,
ponderar*.

*u* quam GHI, A: rule, pull, F: ou; pos q tre curt, presc consonantic
(w). *brun, mult, sudar, quar*.

*y* pos un vocal, e in li comensa de un parol anc avan un vocal, és
consonantic, altriloc vocalic.
*y vocalic* es pronunciat quam Interlingue *i: physica*.

De du o pluri *vocales succedent* chascun es pronunciat. Inaccentuat *i*
e *u* avan vocales e in li combinationes *au* e *eu* (*u* anc li *a* e
li *e* es curt) es tre curt, presc consonantic, e ne posse formar propri
síllabes.

leôn(*), creatôr, mêdie, mediôcri, mêdium, lìngue, linguâl, lìnguìstic,
trottuôre, càude, neutrâl, arcâic, vîa, revûe.

(*) Signes ilustrativ, ne a scrir: ê: long, è: curt.

In plu un strict regul pri li pronunciation long o curt, cludet o apert
del vocales ne existe. Preferibil es li pronunciationes simil a FGHI.

Qui ne conosse alcun de ti pronunciationes posse sequer li indicationes
del <<par4>> quam recomendation, ma ne quam regul strict o complet.

// XXX FIXED -- "r o I" -> "r o l"

[[par4,§4]]§4. In general *vocales accentuat* es passabilmen *long*; ma avan *c
final*, *ch, *x*, o avan pluri consonantes (exceptet r o l con precedent
diferent consonant), e in li curt grammatical paroles ili es *curt*.
*Vocales ínaccentuat* es plu o min *curt*.

*A, i, u* have sempre un medial sonalitá bon distinctibil del altri
vocales. *Accentuat e* e *o* es *cludet*, si ili es long, e avan *m* e
*n, apert* in omni altri casus. *E* e *o ínaccentuat* es plu o min
*cludet*.

marchâr(*), vidêr, venîr, sonôri, constructôr, constructiôn, chèc, iràc,
depèche, paradòx, pâtre, splìttre, câble, pèlle, dilëmma, cömma, mënte,
mönte, atàcca, fòsse, transpòrt, idê, burô, cön, ë, li, më.

(*) Signes ilustrativ, ne a scrir: ê: long e cludet, ë: curt e cludet, è:
curt e apert.

[[par5,§5]]§5. *Li consonantes* es pronunciat quam seque:

*b, d, f, I, m, n, p* quam in AFGI, H (b = b in boca).

====
bon, editer, fratre, long, matre, null, pede.
====

De *duplic consonantes* li duesim es pronunciat solmen si it es
pronunciat altrimen quam li prim. *acceptar, suggester*.

*c* avan e, i, y = ts, altriloc quam k. *centre, reciver, cilindre,
concert, acceptar, electric, electricitá*.

*ch* F, A: sh, G: sch, permisset anc A: ch, H: ch, ma ne recomendat;
avan consonantes quam k. *machine, marchar, chec; chloroform*.

*g* avan e, i, y: AFI, G: dulci sch quam in generös, altriloc AFGHI (gn
maxim possibil g-n, ne nye). *gage, gigant, garage, gimnastica,
guvernar, grisi, suggestion, magnific*.

*gh* in quelc rar paroles avan e, i, y quam g avan a. *ghetto*.

*h* sempre aspirat quam AG. *hom, adherer*.

*j* quam F, A: vision, G: dulci sch quam Journal, dunc quam
Interlingue g avan e. *jurnalist, manjar, jokey*.

*k e kh* quam c dur. *kilogramm, Khedive*.

*ph* quam f (in grec paroles).  *telephon*.

*qu* quam k, sempre sequet de tre curt u: AGI, F e H con u. *quar,
aqua*.

*r* FGHI. *radie, merce*.

*rh* quam r (in grec paroles). *rheumatisme*.

// XXX FIXED -- Removed "altesse".

*s* sonori inter vocales, dur in omni altri casus. *cose, position, pos,
es, roses, divers, sospirar, posta*.

*ss* quam s dur. *casse*.

*sh, sch* quam A: sh, F: ch, G: sch (existe solmen in quelc paroles por
conservar li natural aspecte). *shrapnell, schema*.

*t* es sibilant (quam ts) avan ia, ie, io, iu, si ne un s precede,
altriloc quam AFGHI. *tolerantie, tentar, tentation, hostie*.

*th* quam t (in grec paroles). *theosoph, lithograph*.

// XXX FIXED -- Removed "H". The sound of "v" in Spanish usually is
// "b".

*v* quam AFI, G: w. *venir, dever, nive*.

*w* rar, quam A, curt Interlingue: u. *west*.

*x* dur o dulci, quam AFG, H: examinar. *examinar, extra*.

*y consonantic* quam A, F: yeux, G: j, H: ayustar. *yes, rayon, antey*.

*z* dulci (ds), si possibil, altrimen dur (ts). *zefir*.

*zz* dur (ts). *plazza*.

// XXX FIXED -- "G: ù" -> "G: ü"

[[par6,§6]]§6. Li experientie pruva que *litt variationes* in li pronunciation ne
gena li comprension. Pro to it *es permisset* pronunciar li y vocalic
quam F: u, G: ü, *qu* quam kw, *ch* quam tsch, *j* sempre e *g* sequet
de e, i, y quam dj.

====
cylindre, quadre, marchar, chef, jurnal, gengive.
====

Qui have desfacilitá in li pronunciation de cert combinationes de
consonantes final con li consonantes initial del sequent parol posse
intercalar un *demimut E*, ma sin scrir it.

[[par7,§7]]§7. *Paroles extran* es pronunciat maxim possibil quam in li lingue de
orígine.

====
Champagne, cognac.
====

// Accentuation {{{1
== Accentuation

[[par8,§8]]§8. *Li accentu primari* sta sur li vocal ante li ultim consonant, ma
ne sur li quar síllabes *bil, ic, im, ul*, queles porta li accentu al
precedent síllab, mem si ti-ci es *bil, ic, im, ul*. Un simplic *s* e li
du síllabes *men* e *um* in li fine del parol ne changea li accentuation
del precedent parol-parte. Si ti regules ne es aplicabil, on accentua li
prim vocal del parol.

Si li natural accentuation ne seque ti regul, it es marcat per un
*accentu scrit* (preferibilmen quam in é, tolerat anc è o ê). On posse
omisser li accentu scrit, exceptet sur vocales final, o usar it anc in
altri casus por garantir li desirat accentuation.

In *parol-compositiones* (anc autonom paroles con prefixes) li principal
parte seque ti regules, li altres posse reciver un accentu secundari.

// XXX FIXED -- ínvìa -> invìa
// XXX FIXED -- li práctíca -> li pràctica
// XXX FIXED -- il práctica -> il pràctica

====
Li pòríu(*), familie, àvie, doctòr, formàr, li formàt, li formàte,
formànt; duràbil, elèctric, lògic, li lògica, li lògico, pràctic, li
práctica, il pràctica, il ìndica, il èxplica, dùplic, il dùplica,
multìplic, il multìplica, centùplic, il centùplica, specìfic, il
specìfica, felìci, ùltim, règul, hercùlic, li artìcul, il artìcula;
mìnus, ìris, fòrmes, families, àvies, generàlmen, enèrgicmen, li
fenòmen, màximum, ultimàtum, li legùme; il plìca, il rùla, dìe, dèo,
tùi, vìa, il tràe, it flùe; qualitá, heróe, li logí, il logía, li
fúlmine, it fúlmina, li córpor, il incórpora, li dúbit, il dúbita;
micro-còsmo, anglosaxònic, agricultùra, centimètre, postcàrte,
manuscrìte, genú-articulation, unifòrm, li unifòrme, il unifòrma, il
internationalìsa, ínpracticàbil, índubitàbilmen, li fèrro-vìa, il invìa,
it inflùe, il subtràe, hodíe, il contradí, il retrovèni.
====

(*) In vocabulariums e manuales li scrition del acut es obligatori, ti del
gravis recomendat quam medie didactic por accentus ínscrit: ínscrit, il
inscrí, ìris, ottùplic, il rèplica, il multìplica, specìfic, pacìfic, il
artìcula, il inspùla, il ànima, li ferrovìa, li relvìa, il refá, it
rèsta.

[[par9,§9]]§9. In li *fluent parlada* on ne accentua chascun parol secun li
regul precedent, ma solmen li maxim important paroles del frase.

// XXX REMARK -- In the English version, the following paragraph is
// part of the previous one.

// XXX FIXED -- Removed the useless accent marks of the explanation
// itself, because they have no sense. The example usage is the last
// sentence: "it esset un medicà, ne un medicò":

// XXX FIXED -- ";" -> ":"

On posse sempre aplicar ti regules secun necessitá. Si on vole accentuar
un cert vocal, on posse mem accentuar contra li regul grammatical: it
esset un medicà, ne un medicò.

// Ortografie {{{1
== Ortografie

[[par10,§10]]§10. Interlingue conserva maxim possibil li *aspect international* del
paroles; ma it es recomendat vicear li *duplic consonantes* per li
simplic, exceptet si ili es pronunciat diferentmen o es necessi por
indicar que li precedent vocal es curt o que *s* ne es sonori. Duplic
consonantes in li radica resta anc in li formes derivat.

====
access, suggester, anates, annu, annales, asserfer, aromatic, bloc,
arogant, can, canne, car, carre, present, pressent, li atacca, il
atacca, ataccar, cellul, cellulose, rebell, rebellion.
====

[[par11,§11]]§11. Li *grec gruppes de consonantes: th, chl, chr, ph* es in general
simplificat a: *t, cl, cr, f*, e vice *y* vocalic on scri i. Ma anc li
historic ortografie es permisset.

====
tema o thema, fonograf o phonograph, cloroform o chloroform, simpatic o
sympatic o sympathic.
====

[[par12,§12]]§12. Li *separation sillabic* es líber; preferibil es li separation usat
in parlada o secun li parol-componentes.

[[par13,§13]]§13. *Majuscules* es usat solmen in li comensa del frases, in propri
nómines, in titulationes, e por distincter Vu, Vos, Vor quam formes de
politesse, de vu, vos, vor, si on desira distincter to.

====
Paul, London, Pacifico, Anglia, Danubio, li Senior, su Majestie.
====

[[par14,§14]]§14. Li *acurtationes* maxim frequent es:

// XXX FIXED -- "pm" -> "pm."

sr. o Sr.:: senior
resp.:: respectivmen
sra. o Sra.:: seniora
p. ex.:: por exemple
srta. o Srta.:: senioretta
i. e.:: it es
dr. o Dr.:: doctor
pl.:: ples
etc.:: etcétera
pl. t.:: ples tornar
PS.:: pos-scripte
h.:: hora(s)
v.:: vide
am.:: ante midí
pg.:: págine
pm.:: pos midí
cf.:: confronta
a. c.:: annu current
sq.:: e sequentes
m. c.:: mensu current
nró.:: numeró
a. p.:: annu passat
conc.:: concernent
m. p.:: mensu passat

// Articul {{{1
== Articul

[[par15,§15]]§15. In Interlingue existe un sol *articul definit: li*, por li
substantives masculin, feminin e neutri, singular e plural.

====
li patre, li matre, li table, li patres, li matres, li tables.
====

[[par16,§16]]§16. Un *articul índefinit* existe solmen por li singulare: *un*.
Por li plurale li substantive es usat sin articul.

====
Yo vide un avie. Yo vide avies.
====

[[par17,§17]]§17. Li articul *li* posse *prender li plurale*, si null altri parol
expresse it.

====
On deve metter punctus sur lis i. Ma mult i ne havet punctus.
====

[[par18,§18]]§18. *A li* es contractet a *al*, *de li* a *del*.

====
Il eat al scol. Li árbores del forest es alt.
====

[[par19,§19]]§19. Un *articul partitiv* ne existe.

====
Il trinca aqua. Noi manja fructes.
====

[[par20,§20]]§20. Li articul *definit* indica alquó ja mentionat o conosset, o li
tot specie, li articul *índefinit* alquó ínconosset o ne ancor tractat.

====
Li can quel vu conosse es fidel. Canes es fidel. Li can es fidel.
Fidelitá és un qualitá del tot specie can. Un can de mi fratre es
mordaci, ma li altris ne es tal. Fidelitá es un valorosi qualitá. Li
fidelitá del can (o del canes) es pruvat.
====

// Substantive {{{1
== Substantive

[[par21,§21]]§21. Interlingue lassa al paroles lor *desinenties natural*, e ne
prescri cert vocales final por cert classes de paroles.

====
Cangurú, villa, radio, matre, midí.
====

[[par22,§22]]§22. Li *neutral vocal final -e* trova se in mult substantives por
fixar li corect pronunciation del final consonant, pro eufonie, o por
distincter li substantive del adjectivic o verbal form simil.

====
Pace, image, rose, libre, cable, altruisme, curve, centre, central,
centrale, directiv, directive, marine, circulare, cantate, infinite,
tangente.
====

[[par23,§23]]§23. Un *génere grammatical* ne existe. Omni substantives es
masculin, feminin o neutri secun lor signification.

[[par24,§24]]§24. On posse indicar li génere in li nómines por entes: *-o* indica li
masculin, *-a* li feminin.

====
Anglese, angleso, anglesa, cavall, cavallo, cavalla.
====

Paroles quam patre, matre etc. ne besona finales de sexu, proque ili es
masculin o feminin per se self.

In altri substantives *-o* indica lu special, individual, singulari,
concret, *-a* lu general, extendet, colectiv, comun, anc action, loc e
témpor.

====
rosiero, rosiera, lago, aqua, promenada, plazza, pasca.
====

[[par25,§25]]§25. Quelc substantives forma derivates per adjunter *u* resp. *at* al
radica; ili conserva li *u* resp. *a* anc in li nederivat formes.

====
manu, manual, sexu, sexual, sexualitá, gradu, gradual, graduation,
sistema, sistematic, sistematico, sistematisar, sistematisation, dogma,
dogmatic, dogmatisme, drama, dramatic, dramaturgo, aqua, aquatic, clima,
climatic, climatolog, climatologie, climatologic.
====

[[par26,§26]]§26. Por indicar li *plurale* on adjunte *-s*, pos consonantes
intercalante un *-e-* eufonic, u to es possibil sin changear li
pronunciation del parol.

// XXX FIXED -- "líbre" -> "libre" ("líbre" was used 4 times in the
// document, while the normal "libre" was used 25 times).

====
un libre, du libres, un angul, tri angules, li person, li persones, li
tric, li trics, li plug, li plugs, li album, pluri albums, li tram, du
trams.
====

[[par27,§27]]§27. Li substantive resta ínmutat in omni *casus grammatical*. Es
distinctet solmen li genitive per li preposition *de*, e li dative per
li preposition *a*.

====
Yo vide li sapates de mi fratre.Yo dat li sapates a mi fratre.
====

[[par28,§28]]§28. *Propri nómines* es changeat minim possibil. Por li principal
nómines geografic es selectet in Interlingue li maxim international
parol; altrivez on prende maxim possibil li scrition original.

====
Goethe, Shakespeare; Alpes, Danubio, Germania; London, Berlin, Milano,
Moskwa, Kharkow, Hoang-ho.
====

// Adjective {{{1
== Adjective

[[par29,§29]]§29. Li caracteristic vocal final *-i* trova se in mult
adjectives, precipue por fixar li corect pronunciation del ultim
consonant, e pro distinction pos tipic finales substantivic e
infinitivic.

====
felici, sagi, porosi, organisatori, amari.
====

[[par30,§30]]§30. Mult adjectives posse facilmen esser *substantivat* per adjuntion
del finales *-e, -o, -a*.

====
yun, yune, yunes, yunos, yunas.
====

[[par31,§31]]§31. Por formar un substantive expressent li *general idé* de un qualitá
on adjunte li finale *-um*.

====
li novum, li bellum.
====

[[par32,§32]]§32. Li adjective es *ínvariabil* in génere e númere. _li grand filio,
li grand filia, li grand filios, li grand filias._

[[par33,§33]]§33. Quande li adjective es usat sin substantive e on deve pro cert
rasones indicar li *plurale*, on adjunte *-s*, pos consonantes
intercalante li *-i-* eufonic, u to es possibil sin changear li
pronunciation.

====
Vi pomes, prende li maturis.
====

[[par34,§34]]§34. Por li *comparative* on indica

// XXX FIXED -- "minu (min)" -> "minu

- li *egalitá* per *tam - quam*
- li *majoritá* per *plu - quam*
- li *minoritá* per *minu - quam*

Il es tam grand quam su fratre; il es plu grand quam su fratre; il es
minu grand quam su fratre. Il es plu grand quam yo. Li plu grand libre.

[[par35,§35]]§35 Por li *superlative* on indica

// XXX FIXED -- "maxim (max)" -> "maxim (o max)", plu clar

- li *majoritá* per *maxim* (o *max*)
- li *minoritá* per *minim*

====
Li maxim grand del libres. Li minim grand libre.
====

[[par36,§36]]§36. Por li *superlative absolut on* usa: *tre*, o li sufix
*-issim*.

====
tre grand, grandissim.
====

Por comparar tri o pluri gradus on usa:

====
grand, plu grand, mem plu grand, plu grand ancor, mem plu grand ancor.
====

[[par37,§37]]§37. In omni comparationes on usa: *quam*.

====
egalmen quam, altrimen quam.
====

// Pronómines {{{1
== Pronómines

[[par38,§38]]§38. *Adjectivic pronómines* es tales queles sta avan o pos un
substantive por caracterisar it; ili resta ínvariabil quam ver
adjectives.

*Substantivic pronómines* sta vice un substantive; ili posse prender li
plurale, quam substantives, si necessi.

// Pronómines personal {{{2
=== Pronómines personal

[[par39,§39]]§39. It existe *du formes*, li un por li *subject* (nominative), li
altri por li *object* (acusative o dative, casu obliqui).

[width="100%"]
|===
| Subject            | Object

| yo                 | me
| tu                 | te
| il                 | le
| ella               | la
| it                 | it
| noi                | nos
| vu                 | vos
| ili (illos, ellas) | les (los, las)
|===

Li formes in parenteses es usat solmen in casu de necessitá.

[[par40,§40]]§40. Li pronómin de *politesse* es: *vu* (cf. <<par13>>). On usa it vice tu,
quel expresse un cert intimitá o parentitá.

[[par41,§41]]§41. Li pronómin *índefinit* es: *on*, li *reflexiv: se*, li *reciproc:
unaltru*.

====
On vide se. Ili vide se. Ili vide nos. Vu vide nos. Vu vide vos. Ili
vide unaltru. Noi vide unaltru.
====

[[par42,§42]]§42. *Pos prepositiones* on usa li acusative, o li nominative except
yo e tu.

====
Veni con me! Yo veni con te. Noi ea con le (o il). Vu ea con ella (o
la). Noi parla pri it. On parla pri nos. Yo veni pos vos. Yo labora por
les (o ili).
====

// Pronómines possessiv {{{2
=== Pronómines possessiv

[[par43,§43]]§43. Li formes *adjectivic e substantivic* es egal; ma por li
substantivic on posse usar li *articul*, secun li nuancie o li regul del
lingue matrin, e ili prende li *plurale*, si necessi.


[width="100%"]
|===
|mi | tui | su | nor | vor | lor
|===

====
To es mi. To es li mi. To es mi libres. To es li mis. To es tui. To es
li tui. To es lor. To es li lor. To es li lores. Vi nor parapluvies. Li
mi es plu grand quam vor, o: quam li vor. Vidente nor canes yo constata
que li tuis súpera li mis in vìvacitá, o: que tuis súpera mís in
vivacitá, etc. To es lores; to es li lores. Ples far lu tui. Ples da me
tui libre. Il deve far li su.
====

// Pronómines demonstrativ {{{2
=== Pronómines demonstrativ

[[par44,§44]]§44. Li formes *adjectivic e substantivic* es egal; ma li substantivics
prende li plurale e posse prender li sexu, si to in rar casus es
necessi.

[[par45,§45]]§45. Por monstrar alquó on usa generalmen: *ti*. Solmen si on vole
indicar explicitmen li proximitá o lontanitá on adjunte li adverbies
*ci* o *ta* med un strec ligant.

====
Ti libre es bell. Yo vide ti libres. Yo vide tís. Ti-ci table es solid.
Ti-ci tables es solid. Tis-ci es solid, ma tis-ta ne es tal.
====

Li *sexu* posse exceptionalmen esser indicat per li pronómin personal.

====
il-ti, il-ci, ella-ti, illos-ci, ellas-ta.
====

[[par46,§46]]§46. *Ti, tal e tant* es li corelatives de *quel, qual e quant*. (Tant
ne posse prender li plurale, proque it self indica li plurale.)

====
Quel libres vu prefere? Ti libres, queles anc vu ama. Qual libres vu
prefere? Tal libres, queles raconta de viages. Yo ama tal homes. Yo ama
tales. Il es sempre tal. Quant persones esset ci? Tant quam yer. Tant
quant yer.
====

[[par47,§47]]§47. Li *neutri form* por coses e factes es: *to*, respondent al
question: *quo*, de quel on forma: to-ci e to-ta.

====
To es mi libre. Yo save to (li facte, que to es tui libre).
====

[[par48,§48]]§48. Li *pronómin o articul lu* servi por expresser to quo es
impersonal, neutri o abstract. It significa generalmen: to quo es
(li)...

====
De lu sublim a lu comic es sovente solmen un passu. Lu nov de ti
conception es...
====

// Pronómines relativ e interrogativ {{{2
=== Pronómines relativ e interrogativ

[[par49,§49]]§49. On usa li sam pronómines, relativ e interrogativ, adjectivic e
substantivic.

[[par50,§50]]§50. Li *maxim general es: quel* (plural: *queles*), usat por coses,
factes e persones.

====
Quel cité es li maxim grand? Quel es li maxím grand cité? Queles es li
maxim grand cités? Quel cités es li maxim grand? Li maxim bell flore
quel yo conosse es li rose. Li maxim grand cités queles yo conosse es
New York e London. Il ne save, quel grand cités il va vider.
====

[[par51,§51]]§51. Por *coses e factes* on usa: *quo*, por *persones: qui*.

// XXX FIXED -- víde -> vide

====
Quo vu vide? Quo vu vole far? Yo ne save, quo yo vole far. Yo ne
comprende to quo il ha dit. Qui es ta? De qui es ti chapel? A qui tu dat
li moné? Qui vu saluta? Qui saluta vos? Li amico, a qui vu dat li libre,
esset content. Beat es tis, qui (o queles) ne vide, ma támen crede. Nor
lingue fa un constant progress, quo (quel facte) tre joya me.
====

[[par52,§52]]§52. Si *pluri relationes* de un pronómin relativ es possibil, li
ínmediat vale. Si un altri deve valer, on indica to per pronómines
personal o demonstrativ, o per comma.

====
Yo videt li fratre de mi amico quel arivat yer. Yo videt li fratre de mi
amico, il quel (o il qui) arivat yer. To es li sestra de mi amico, ella
qui arivat yer. Yer yo videt li possessor del dom, qui (o il qui, o ti
qui, o li quel, o ti quel) es in li cité. Yer yo videt li possessor del
dom quel es in li cité. Yer yo videt li possessor del dom, quel es in Ii
cíté.
====

[[par53,§53]]§53. Por expresser li *qualitá* on usa: *qual*, por li *quantitá:
quant*.

====
Qual homes esset ci? Qual es li aqua hodíe, calid o frigid? Yo ne save
qual it es. Qual compositor, tal musica. Quant il deve dar vos ancor? Yo
ne save, quant il ha dat le. Quant vive, tant espera.
====

// Pronómines índefinit {{{2
=== Pronómines índefinit

[[par54,§54]]§54. Li prefix *al-* da pronómines indicant alquó índeterminat, li
prefix *ne-* tales indicant li absentie, li negation, e li sufix
*-cunc* fa definit pronómines relativ índefinit.

|===
| alquel  | nequel  | quelcunc
| alqual  | nequal  | qualcunc
| alquant | nequant | quantcunc
| alquó   | nequó   | quocunc
| alquí   | nequí   | quicunc
| alcun   | necun   |
|         | necos   |
|===

====
Si alcun fémina parla pri alquó, ella pensa pri alquí. Quicunc va venir,
yo ne es in hem. Quocunc vu di, ples dir li veritá! Quelcunc labor vu
fa, e in qualcunc maniere e por quicunc, ples far it bon! A quicunc tu
da li moné, da it solmen contra quittantie.
====

[[par55,§55]]§55. Altri *pronómines índefinit es*:

On, self, li sam, quelc, null, chascun, omni, omnicos, ambi, altri,
altricos, céteri, pluri, mult, poc, un poc, cert, un cert, mani, singul,
tot.

====
Yo prefere far it self. Ili retornat in li sam loc. Chascun hom es
forjero de su propri fortun. Ples dar me quelc libres; yo have quelc
líber hores por leer. Pleser a omnes on ne posse, es arte quel nequí
conosse. Ja pluri annus yo vive in ti cité. Il have poc espera. Il have
un poc espera. Yo conosse un cert senior Blanc; ma yo ne es cert, esque
il es ci. It es tot egal, ca vu vide li tot munde o quelc partes de it.
====

// Numerales {{{1
== Numerales

[[par56,§56]]§56. Li *númeres cardinal* es:

// XXX FIXED -- niantnin -> ninantnin

0 null 1 un 2 du 3 tri 4 quar 5 quin 6 six 7 sett 8 ott 9 nin 10 deci 11
deciun 12 decidu 13 decitri 14 deciquar 15 deciquin ... 19 decinin 20
duant 21 duantun 22 duantdu . .. 30 triant 40 quarant 50 quinant 60
sixant ... 90 ninant ... 99 ninantnin 100 cent 101 cent un 102
centdu... 110 centdeci 111 cent deciun ... 119 cent decinin 120 cent
duant 121 cent duantun ... 130 cent triant ... 199 cent ninantnin 200
ducent 201 ducent un ... 210 ducent deci 300 tricent ... 999 nincent
ninantnin 1000 mill 1001 mill un ... 1099 mill ninantnin 1100 mill cent
1101 mill cent un ... 1999 mill nincent ninantnin 2000 du mill 2001 du
mill un ... 2345 du mill tricent quarantquin ... 99{nbsp}000 ninantnin
mill ... 100{nbsp}000 cent mill ... 100{nbsp}999 cent mill nincent ninantnin
200{nbsp}000 ducent mill ... 201{nbsp}000 ducent un mill ... 299{nbsp}999 ducent
ninantnin mill nincent ninantnin ...
456{nbsp}789 quarcent quinantsix mill settcent ottantnin ... 1{nbsp}000{nbsp}000 un
million 1{nbsp}000{nbsp}001 un million un ... 2{nbsp}000{nbsp}000 du milliones ...

- mill milliones = un milliard
- un million milliones = un billion
- 1{nbsp}000{nbsp}000 = un million
- 1{nbsp}000{nbsp}000^2^ = 1{nbsp}000{nbsp}000{nbsp}000{nbsp}000 = un billion
- 1{nbsp}000{nbsp}000^3^ = un million billiones = un trillion
- 1{nbsp}000{nbsp}000^4^ = un million trilliones = un quadrillion

[[par57,§57]]§57. Li *númeres ordinal* es format per adjunter li finale
*-esim*: unesim* (apu *prim*), *duesim* (apu *secund*), *triesim*, etc.

[[par58,§58]]§58. Li *númeres fractionari* es egal al ordinales, ma ordinarimen
on vicea li unesim quar per: un *tot*, un *demí, un ters*, un *quart*.

====
du ters, tri quart, quar quinesim, etc.
====

[[par59,§59]]§59. Li *fractiones decimal* es pronunciat

- 3,78349 = tri comma sett ott tri quar nin,
- 0,25 = null comma du quin.

[[par60,§60]]§60. Li *numerales multiplicativ* es format per adjunter li finale
*-uplic* (pos vocales: -plic):

====
unuplic (simplic), duplic, triplic, quaruplic (quadruplic), quinuplic
(quintuplic), sixuplic, settuplic, ottuplic, ninuplic, deciplic,
deciunuplic, deciduplic, duantuplic, centuplic, centunuplic, etc.
====

[[par61,§61]]§61. Li *numerales iterativ* es format per: *vez*.

====
du vez o duvez, tri vez, centvez, mult vez o multvez o mult vezes.
====

[[par62,§62]]§62. Li *numerales colectiv* es format per li finale: *-ene*.

====
li unité, pare, triene, quarene, quinene, decene, deciduene, centene.
====

[[par63,§63]]§63. *Altri numeral expressiones* es p. ex.:

====
chascun triesim vez, tri e tri, quar e quar. Li soldates marcha quar e
quar.
====

[[par64,§64]]§64. *Calcul aritmetic*.

Addition: 12 + 10 = 22 decidu plus deci es duantdu.

Subtraction: 21 - 3 = 18 duantun minus tri es deciott.

Multiplication: 3 x 8 = 24 tri vez ott, o tri multiplicat per ott, o tri
per ott es duantquar.

Division: 69 : 3 = 23 sixantnin sur tri, o dividet per tri es duanttri.

Potentiation: 6^2^ = 36 six quadrat, o six in duesim potentie, o six in
duesim es triantsix.
2^3^ = 8 du in cub, o du in triesim potentie, o du in triesim es ott.

Radication: √49 = 7
radica quadratic, o duesim radica ex quarantnin es sett.
∛8 = 2 radica cubic, o
triesim radica de ott es du.

// Verb {{{1
== Verb

[[par65,§65]]§65. In Interlingue existe *un sol* e *unitari conjugation* per
adjuntion de cert consonantes al tema presentic.

// XXX FIXED -- "al tema verbal (radica plus prefixes e sufixes)" ->
// "al tema verbal":

[[par66,§66]]§66. Li *tema presentic* es format per adjunter un del tri vocales
"a", "i", "e"
al tema verbal. Ti vocal es
caracteristic por chascun verb e resta ínvariabil in omni formes del
conjugation.

[width="100%"]
|===
| Tema verbal | Tema presentic

| fabric      | fabrica
| exped       | expedi
| construct   | constructe
|===

Li concernent vocal caracteristic apari in omni formes del conjugation;
on posse dunc basar li tot conjugation sur li tema presentic, e far li
distinctiones solmen per li final consonantes, identic por li tri
gruppes de verbes.

[[par67,§67]]§67. Li unesim, duesim e triesim person, singulare e plurale, es
distinctet solmen per li pronómin; li verb self resta ínmutat.

[[par68,§68]]§68. Li *infinitive* es format per adjunter *-r* al tema presentic:

[width="100%"]
|===
| fabricar | expedir | constructer
|===

[[par69,§69]]§69. Li *presente* es egal al tema presentic:

// XXX FIXED -- "il constructer" -> "il constructe"

[width="100%"]
|===
| yo fabrica | tu expedi | il constructe
|===

Li verb *esser* have un special abreviat form del presente: *es*, vice
esse, pro su grand frequentitá.

[[par70,§70]]§70. *Li participie passat* (anc *participie passiv*) es format per
adjunter *-t* al tema presentic:

[width="100%"]
|===
| fabricat | expedit | constructet
|===

Li participie passat es usat anc quam *passate simplic*:

====
noi fabricat, vu expedit, ili constructet.
====

[[par71,§71]]§71. Omni *composit témpores passat* es format per li verb auxiliari
*har*. lli indica actiones terminat.

Li *passate composit* es:

====
- Yo ha fabricat.
- Tu ha expedit.
- Il ha constructet.
====

Li *passate anteriori* es:

====
- Noi hat fabricat.
- Vu hat expedit.
- Ili hat constructet.
====

[[par72,§72]]§72. Li *future simplic* es format per li auxiliare *va*:

====
- Il va fabricar.
- Ella va expedir.
- On va constructer.
====

Li *future anteriori* es:

====
- Yo va har fabricat.
- Tu va har expedit
- Il va har constructet.
====

[[par73,§73]]§73. Li *conditionale simplic* es format per li auxiliare *vell*:

====
- Noi vell laborar.
- Vu vell expedir.
- Ili vell constructer.
====

Li *conditionale passat* es:

====
- Il vell har fabricat.
- Il vell har expedit
- Ili vell har constructet.
====

[[par74,§74]]§74. Li *participie presentic* (anc *participie activ*) es format
per adjunter *-nt* al tema presentic:

[width="100%"]
|===
| fabricant | expedient | constructent
|===

Li verbes con *-i* prende *-ent* vice *-nt* por retrovar li derivates
international, p. ex. convenientie, provenientie.

Li *adverbial form* es usat quam *gerundie* (= durant que o per to que)
per adjunter *-e*:

[width="100%"]
|===
| fabricante | expediente | constructente
|===

Existe anc *formes progressiv*:

[width="100%"]
|===
| il es fabricant  | il es expedient | il es constructent
|===

[[par75,§75]]§75. Li *imperative* es egal al presente sin pronómin:

[width="100%"]
|===
| fabrica! | expedi!  | constructe!
|===

Del verb *esser* on prende li complet form: *esse*.

Existe un *form de politesse per ples* (de pleser) con infinitive:

[width="100%"]
|===
| ples fabricar | ples expedir | ples constructer
|===

[[par76,§76]]§76. Li *optative* es format per *mey* con infinitive:

[width="100%"]
|===
| il mey fabricar | il mey expedir | il mey constructer
|===

li *hortative* per *lass*:

[width="100%"]
|===
| lass nos fabricar | lass nos expedir | lass nos constructer
|===

[[par77,§77]]§77. Li *formes passiv* es format per li verb auxiliari *esser*:

====
- It es perlaborat.
- Ili hat esset expedit.
- Ili esset perlaborat.
- It va esser expedit.
- It ha esset perlaborat.
- Ili va har esset expedit.
- It vell esser constructet.
- Ili vell har esset constructet.
- It mey esser constructet.
====

Ti maniere formar li passive es comun al maxim mult lingues national. Ma
quelcvez it es necessi distincter, ca un action dura ancor o es ja
finit. In ti casus on usa altri verbes, p. ex.:

====
- Li dom ea constructet. Li dom sta constructet.
- Li libre eat printat. Li libre stat printat.
====

In mult casus li passive posse esser expresset per substantives o per li
form reflexiv:

====
- Li dom es in construction.
- Li libre esset in printation.
- Li jurnal printa se rapid.
- Li cose explica se simplicmen.
====

[[par78,§78]]§78. *Vice li subjuntive* on usa in general li indicative. Solmen in
rar casus exceptional (p. ex. in juristic documentes) on posse usar un
form subjuntivic per adjunter *-ye* al presente del verb o del verb
auxiliari:

====
Il di que il la amaye. Il dit que il la haye amat.
====

// Verbal derivation {{{2
=== Verbal derivation

// XXX FIXED -- "millenes" -> "milles":

[[par79,§79]]§79. In omni lingues milles de substantives e adjectives es format ex
li radica verbal per adjunter finales. Ti paroles sembla esser format
tam ínregularimen, que li maxim conosset anteriori lingues international
ha renunciat incorporar les in su sistema de derivation e ha viceat les
per artificial constructiones.

// XXX FIXED -- "internàtional radicas" -> "international radicas"

Al creator de Interlingue, *Prof. Edgar de Wahl*, reveni li merite, har
decovrit quelc simplic regules por formar ti paroles internationalmen
conosset per adjunter international finales a international radicas.

[[par80,§80]]§80. Li sufixes: *ion, or, ori, iv, ura* ne es adjuntet al tema verbal o
al tema presentic, ma al *tema perfectic*.

Ti unesim gruppe de finales es adjuntet a verbes expressent un action o
transformation, al talnominat *verbes dinamic*.

Li tema perfectic es trovat per li *Regul de Wahl*, li clave al unic
lingue vermen international e in sam témpor regulari:

On supresse li *r* resp. *er* del infinitive. Si li rest fini per vocal,
on adjunte *t*, si it fini per *d* o *r*, on vicea ti consonant per *s*,
in omni altri casus li rest self es li tema perfectic.

[width="100%"]
|===
| Infinitive  | ...       | Tema perfectic

| adherer     | adher     | adhes
| constructer | construct | construct
| crear       | crea      | creat
| distribuer  | distribu  | distribut
| expedir     | expedi    | expedit
| exploder    | explod    | explos
|===

// XXX FIXED -- "ye li verbes" -> "e che li verbes":

// XXX TODO -- Copy the explanation about the verb stems into the individual
// entries:

On posse anc dir, que li sufixes: *-ion, -or, -ori, -iv* e *-ura* es adjuntet
che li verbes con *ar* e *ir* al participie passat, e che li verbes con
*er* al
radica, intercalante *t* pos vocal final e mutante un final *d* o *r* a
*s*.

// XXX FIXED -- "cretiv" -> "creativ":

[width="100%"]
|===
| crear    | expedir    | constructer
| creat    | expedit    | construct
| creation | expedition | construction
| creator  | expeditor  | constructor
| creatori | expeditori | constructori
| creativ  | expeditiv  | constructiv
| creatura | garnitura  | structura
|===

// XXX TODO -- Join these tables.

[width="100%"]
|===
| distribuer   | exploder  | adherer
| distribut    | explos    | adhes
| distribution | explosion | adhesion
| distributor  | revisor   | precursor
| distributori | revisori  | cursori
| distributiv  | explosiv  | adhesiv
| scritura     | tonsura   |
|===

*Quin verbes* forma ti derivates un poc diferentmen, usante li
international formes:

[width="100%"]
|===
| Infinitive | Derivate | Vice

| seder      | session  | sesion
| ceder      | cession  | cesion
| verter     | version  | vertion
| venir      | vention  | venition
| tener      | tention  | tenion
|===

[[par81,§81]]§81. Che li tri verbes: *far, dir, scrir* on posse formar li derivates
per li complet radicas: *fact, dict, script*.

// XXX FIXED -- "consonantgruppe -nct-" -> "consonantgruppe -ct-":

Che li verbes con li consonantgruppe *-ct-* on posse omisser li *c*,
precipue in nederivat formes.

====
Contrafaction o contrafation, factor o fator, malediction o maledition,
prescription o prescrition. Distincter o distinter, distinction o
distintion, conjunction, conjunter.
====

[[par82,§82]]§82. Li *finale -ntie* es adjuntet al tema presentic de verbes
expressent un statu, al talnominat *verbes static*.

[width="100%"]
|===
| tolerar  | tolerantie
| provenir | provenientie
| exister  | existentie
|===

Quam in li participie presentic on intercala *e* pos *i* del verbes in
*ir*. Ti finale es solmen un combination del finale del participie
presentic
*-nt* con li sufix *-ie*.

// XXX FIXED -- "presen-tic" -> "presentic":

[[par83,§83]]§83. In analog maniere adjunte se li sufix *-nd* al tema presentic:

[width="100%"]
|===
| demonstrand | vendiend | leend
|===

[[par84,§84]]§84. Li sufix *-ment* anc es adjuntet al tema presentic:

[width="100%"]
|===
| fundar  | fundament
| mover   | movement
| experir | experiment
|===

Si li radica de un verb con *er* fini per vocal, li *e* desapari:

====
arguer, argument, compleer, complement.
====

[[par85,§85]]§85. Du sufixes adjunte se al radica verbal in du formes diferent secun
li vocal caracteristic: *-abil, -ada* ye *a* resp. *-ibil, -ida* ye *i*
o *e*:

[width="99%"]
|===
| durar    | durabil
| promenar | promenada
| currer   | currida
| posser   | possibil
| audir    | audibil
| vomir    | vomida
|===

[[par86,§86]]§86. *Li altri sufixes* es adjuntet directmen al radica verbal:

// XXX FIXED -- "vìvaci" -> "vivaci"

[width="100%"]
|===
| criticar | criticachar
| furter   | furtard
| lavar    | lavera
| rafinar  | rafinage
| reservar | reservuor
| spiar    | spion
| valer    | valore
| viver    | vivaci
|===

[[par87,§87]]§87. *Substantivation direct:* On posse anc usar quam substantive li
radica verbal con li desinenties substantivic, o li <<par80,tema perfectic>> con o
sin desinentie substantivic:

// XXX FIXED -- "lì resultat" -> "li resultat"

====
li pense, li pensa (plu proxim al action), li vende, li crede, li
response, li vise, li flut, li resultat, li extracte, li tribut.
====

Li <<par80,tema perfectic>> sin finale es usat anc quam *adjective*:

====
devot, apert, pervers.
====

// Adverbies {{{1
== Adverbies

[[par88,§88]]§88. Por *indicar un qualitá* de un substantive on usa un adjective,
de altri paroles un adverbie.

====
Un prudent mann acte prudentmen.
====

[[par89,§89]]§89. In Interlingue on posse usar li adjective vice li adverbie, si li
sens es clar.

====
Il ha bon laborat. Noi serchat long.
====

[[par90,§90]]§90. It existe *adverbies primari* sin special finale, e *adverbies
derivat* de adjectives per adjunter li ínaccentuat finale *-men*.

// XXX FIXME -- Remove adjectives: natural, respectosi:

====
tre, sempre, deman, natural, naturalmen, respectosi, respectosimen.
====

[[par91,§91]]§91. Vice special adverbies on usa multvez *adverbial expressiones*,
format per prepositiones.

====
ex memorie, in general, in fine, per hasard.
====

[[par92,§92]]§92. Li *comparative e superlative* es format in li sam maniere quam
in li adjectives.

====
Il parla li lingue fluentmen. Il scri in min elegant maniere. Il salutat
le maxim respectosimen. Si vu es fatigat, vu labora min rapidmen quam si
vu es reposat.
====

[[par93,§93]]§93. Secun li sens on posse *gruppar li adverbies* in adverbies de
maniere, de quantitá, de loc, de témpor, e adverbies afirmativ, negativ
e de dúbit.

[[par94,§94]]§94. Li *adverbies de maniere* responde al question: *qualmen?*

qualmen, quam, talmen, tam, alquam, nequam, solmen, apen, tot, totalmen,
totmen, ne totmen, totmen ne, presc, poc, poc a poc, mem, precipue,
junt, anc, denove, tamen, malgré to, dunc.

====
Yo ne save, qualmen il posse laborar tam rapidmen quam un machine, nam
il fa tant rapid, que on presc ne posse sequer. Il dit to quam rey. Il
ne acte quam un rey. It es impossibíl far it talmen. Il ha fat it alquam
(={nbsp}in alcun maniere). Il posse far it nequam (={nbsp}in necun
maniere). It es tot
egal, esque vu vide li tot munde o quelc partes de it. Il ha totalmen
miscomprendet ti libre. Ma tamen on ne deve judicar solmen la, proque
ella ne totmen comprende li lingue, e to es totmen ne su propri culpa.
On posse mem dir que to es precipue li culpa del altris.
====

[[par95,§95]]§95. Li *adverbies de quantitá* responde al question: *quant?*

quant, tant, sat, suficent, nequant, alquant, tre, tro, circa, mult,
poc, un poc, quelcvez, multvez, sovente, plu, adplu, sempre, sempre plu,
sempre plu mult, sempre plu mult ancor, min, plu o min, maxim, admaxim,
minim, adminim, maxim possibil, minim possibil, maximal, minimal,
proxim, ancor, plus, minus.

====
Quant persones esset ci? Tant quant yer. Circa duant persones sedet
circum li table, adminim tri persones tro mult, proque li table havet
plazza solmen por admaxim 17 persones. Poc a poc ili va observar un poc,
que ili labora per un metode poc apt por ti scop.
====

[[par96,§96]]§96. Li *adverbies de loc* responde al question: *u*, *a u*, *de* *u?*
(Li preposition *a* es in combinationes viceat per *ad*.)

u, ci, ta, alcú, necú, partú, ucunc, supra, infra, circum, éxter, extra,
intra, ínter, detra, levul, dextri, proxim, lontan. A ci, a ta, adavan,
retro, up = adsupra, a bass, adinfra, de infra, préter.

====
U vu ha comprat ti libre? In un librería u on trova sempre li maxim
recent libres. Alcú vu certmen va trovar li tant serchat flor. Ma ucunc
vu sercha, ples nequande obliviar, que partú es bell flores. Yo espera
que to es finalmen partú sat conosset. In vor proxim lettre vu deve
scrir un poc plu del eclesia proxim vor dom. Il venit de infra, passat
préter nos, e eat adsupra. Ma fórsan il va bentost ear retro in su cava.
====

[[par97,§97]]§97. Li *adverbies de témpor* responde al question: *quande?*

quande, unquande, alquande, nequande, quandecunc, alor, tande, ínterim,
nu, strax, subitmen, just, justmen, bentost, tost, tard, temporan,
solmen, ne ante, sovente, sempre, ne plu, antey, poy, depoy, desde, in
ante, ja, ancor, ne ancor, adplu, ulteriori, hodíe, ho-annu, ho-témpor,
deman, posdeman, yer, anteyer, unvez, durante, finalmen, in fine.

====
Quande yo visitat le, il racontat me, que unquande il ha incontrat la,
ma nequande plu desde alor. Nu il es old e ínterim il ha mult laborat.
Just nu vu posse far it, proque vu es tost, ma bentost it vell esser tro
tard. Presc sempre il es ci, solmen deman il va departer e retornar ne
ante deci horas del vésper, e fórsan solmen posdeman. In ante yo posse
dir vos solmen to, nam it es ancor íncert, ca il ne deve subitmen
changear su projectes.
====

[[par98,§98]]§98. Li *adverbies de afirmation, negation, dúbit* es: *yes, no, ne, ne
plu, si, ya, fórsan, sin dúbit*.

====
Esque vu ne ha videt le? Si, il esset ya in li scol e sin dúbit ne plu
va retornar ante midí.
====

// Prepositiones {{{1
== Prepositiones

[[par99,§99]]§99. Omni prepositiones sta *ínmediatmen avan lor complement*. lli es
ínvariabil.

*Pos prepositiones* on usa li *acusative* del pronómines, o li
nominative except yo e tu.

[[par100,§100]]§100. Li *usation del prepositiones* in li lingues national es
multvez contradictori. Pro to on deve sempre usar li prepositiones secun
lor propri signification.

In casus, u on ne trova un preposition con li exact sens a expresser, on
usa li preposition *ye*, quel indica un relation índefinit. Ma tre
sovente on posse usar li prepositiones *a, de* e *in*, queles have pluri
significationes.

[[par101,§101]]§101, Multvez li relation es clar anc *sin preposition*. Li *verbes* es
p. ex. usat maxim possibil sin preposition, con ínmediatmen sequent
object, si li relation es clar; ma li usation de un sensconform
preposition es sempre permisset.

====
Il intrat li chambre. Il intrat in li chambre. Il montat li monte. Il
montat sur li monte. Yo memora li cose. Yo memora pri li cose. Il
prepara un viage. Il prepara se por un viage.
====

[[par102,§102]]§102. Li *maxim frequent prepositiones* es:

// XXX FIXED -- "sedet intra li fable" -> "sedet infra li table"
// XXX FIXED -- "ínfra" -> "infra"
// XXX FIXED -- "ami'cos" -> "amicos"
// XXX FIXED -- ínterlingue -> Interlingue
// XXX FIXED -- "to sín saver" -> "to sin saver"
// XXX FIXED -- "rich genito res" -> rich genitores"
// XXX FIXED -- "Multís vell prefer viver in li rure" ->
// "Mult vell prefer viver in li rure" ->

a::

(In combinationes anc *ad*.)
+
====
Il dat li flores a su amata. Yo dat un
libre a Paul. Yo dat le un libre. Yo dat un libre a le. Un
epistul a nor societé. Yo viagea a New York. Li vapornave ea
a Lisboa. Clar a departer. Un error a regretar. Quo vu di pri
mi arm a foy? Yo selectet it de tri armes a frs. 40.—. Yo va
atender vos a tri horas al exeada nord del station.
====
+
*ad* posse esser combinat con altri prepositiones e adverbies
por far plu clar li sens:
+
====
adavan, adsur, adin, ad-in, etc.
====

along::
+
====
Ili promenat along li rive del lago.
====

ante (temporal)::
+
====
Il vivet ante Christ. Li sestra venit tri semanes
ante su fratre, ante tri mensus (o tri mensus ante nu). Ella va departer
ante fine de tri mensus. Felicitá veni ante richesse. Il incontrat le
ante li dom.
====

apu::
+
====
Li dom sta proxim li eclesia, ma ne apu it. Li turre de nor
eclesia sta apu li eclesia, ma ne al eclesia, proque it ne tucha li
eclesia self, ma lassa un passage inter li du. Li dolore fisic es nequó
apu li dolore mental.
====

avan (local)::
+
====
Li patre promenat avan li dom. Li patre promenat a avan
li dom. Li patre venit de avan li dom. Il incontrat le avan li dom.
====

caus::
+
====
Caus vor intervention yo arivat ante minocte avan mi dom.
====

che::
+
====
Il logiat che su fratre. Durante long témpor il vivet che li
negres. Che li canes on distincte divers rasses.
====

circum::
+
====
Circum li eclesia stat alt árbores. Li terra torna circum li
sole.
====

cis::
+
====
Francia es situat cis li Pirenés.
====

// XXX FIXED -- "lacrimes" -> "lácrimes"

con::
+
====
Li filio ea con su patre along li fluvie. Ella stat con lácrimes
in li ocules con su marito avan li station.
====

contra::
+
====
Li unes laborat contra li altres. Il exchangea su bicicle
contra combustibiles. Li aeroplan aviat contra li gratta-ciel.
====

de::
+
====
Li dom de mi patre. Li dramas de Schiller. Un senior de Paris.
Li maxim grand de omnis. Un vase de aure. Ti lettres es scrit
de un poet per scri-machine. Li moné de un povri vidua ha
esset furtet per un escapate del prison, nascet de rich genitores.
Il vivet lontan de su patre, de quel il nequande audít
alquó.
====

desde::
+
====
Desde du annus il neplu posse laborar. Il vendi chapeles desde
frs. 20.—. Il prendet li tren de Roma desde Milano.
====

detra::
+
====
Detra li dom esset un grand corte.
====

durante::
+
====
Durante li estive li infantes ludet sur li plazza. Li un de
su filios studiat medícina, durante que li altri ne volet studiar.
====

ex::
+
====
Il venit ex su chambre. Yo trinca ex li glass. Traductet ex german
a Interlingue. Li vestiment es fat ex pur lan. Noi audit in
li radio un concert de Beethoven ex London.
====

extra::
+
====
Il vivet extra su patria. Soledí ili devet luder extra li
audir-distantie.
====

in::
+
====
Mult persones vive in li cité. Mult vell preferer viver in li
rure. In omni ocasion il eat al forest vice al scol, adminim decivez in
min quam un annu.
====

infra::
+
====
Li aviones vola infra li stratosfere. Il sedet infra li table,
e li patre supra. Sub li table esset un can. Súper li table esset li
lampe e sur li table un libre.
====

inter::
+
====
Ili esset li sol tranquil scoleros inter mult bruiosi. Inter
New York e Paris. Inter du e tri horas. Un conversation inter du
amicos. Divider un heredage inter li filios. Un guerre inter du
nationes.
====

intra::
+
====
Ili ne posset penetrar intra li mures del cité. Yo va
retrovenir intra tri hores.
====

malgré::
+
====
Malgré su grand efortíes il ne posset perforar li mur.
====

med::
+
====
Med un bon instruction on va plu bon successar in li vive.
====

per (medie)::
+
====
Il defendet se per un gladíe. Il salvat se per natar. Li
moné esset furtet per un ínconosset hom.
====

por (scope)::
+
====
Un libre por omnes e por nequí. On manja por viver, on ne
vive por manjar. Yo comprat un libre por frs. 10.—, grand por su precie.
It sufice por long, ne solmen por deman.
====

pri (dominia)::
+
====
Noi parlat pri politica. Yo ha mult pensat pri vos.
====

pro (cause)::
+
====
Ella plorat pro joya. Yo mersía pro vor auxilie.
====

pos::
+
====
Pos quelc dies ili tamen atinget lor scope. Li capitano vení pos
li major.
====

préter::
+
====
Ili passat préter li dom de mi patre.
====

// XXX FIXED -- "proxím" -> "proxim" (in li exemple)

proxim::
+
====
Il habitat proxim li cité.
====

secun::
+
====
Secun li prescription to ne es permisset.
====

sin::
+
====
Il fat to sin saver pro quo.
====

sub::
+
====
Sub li árbor on trovat mult fructes sur li table. Li carre
vacilat sub li carga. Il havet plu quam 100 persones sub su autoritá. Il
scrit sub un pseudonim, que mem sub Napoleon on ne devet laborar sub tal
mal conditiones.
====

súper::
+
====
Súper li árbor volat un avie; quelc altris sedet sur it e celat
se detra e sub su folies.
====

sur::
+
====
It venit de sub li table súper it e poy sedet sur it.
====

til::
+
====
Yo laborat til decidu horas. Til li extrem fine del munde, su
influentie es sentibil, til que un altri va vicear le.
====

tra::
+
====
Yo ha videt le tra li fenestre promenar tra li campes.
====

trans::
+
====
Li tren ea tra li túnnel del Sanct Gotthard trans li Alpes.
====

ultra::
+
====
Ultra francesi e german il parla anc Interlingue.
====

vers::
+
====
Li avie volat vers li sole.
====

vice::
+
====
Il venit vice su patre, ma solmen pos tri semanes vice intra du
semanes.
====

vis a vis::
+
====
Vis a vis li eclesia on vide li scola.
====

ye::

It es usat, si exceptionalmen null altri preposition es apt:
+
====
Ye (in) omni ocasion il eat in li forest vice al scol. Yo va atender vos
precisi ye (a) tri horas sur li plazza del scola. Yo vide la ye (che,
avan, al) li triesim dom. Ili pariat ye (per, de) quin francs.
====

[[par103,§103]]§103. Mult *prepositional expressiones* es format per adverbies e
adjectives:

====
Mersí vor auxilie, yo posset fìnir li labor ante li fixat termin,
exceptet li ultim págines, queles ne es conform al programma, Concernent
vor ultim question, yo posse solmen dir, que il esset in medie del
chambre ínter su infantes.
====

// Conjunctiones {{{1
== Conjunctiones

[[par104,§104]]§104, Conjunctiones de *coordination* es:

e, e ... e, o, o ... o, ni, ni ... ni, sive ... sive, ma, nam, tamen,
ergo, dunc, plu ... plu, nu, nu ... nu.

====
E li patre e li matre devenit ciec. O il veni o noi deve cluder li
porta. Il certmen ne va manjar ni trincar, nam il ni manja carne, ni
trinca alcohol. Sive tu consenti, sive tu ne consenti, noi tamen va far
it; ma plu tu obstina te, plu tu va esser isolat. Nu, tu posse far quo
tu vole. Il ne plu es normal in li cap, nam nu il ride, nu il plora sin
visibil motive.
====

[[par105,§105]]§105. Conjunctiones de *subordination* es: *que, si, quam, esque, ca,
quasi, benque, etsí*.

====
On ne posse saver, ca il veni o ne, nam benque il es li marito, il es
quasi li sclavo de su marita. Si il veni, on ne deve questionar le pri
to, quam si on vell saver nequó. Il ne posse dir in ante, si il posse
venir; nam ca il posse venir o ne, to depende de su marita.
====

[[par106,§106]]§106. Mult conjunctiones e conjunctional expressiones es *composit* ex
prepositiones o prepositional expressiones o adverbies o adverbial
expressiones con *que* e *quam*.

====
per que, por que, pro que, pos que, ante que, durante que, sam quam,
desde que, sin que, tant que, suposit que, in condition que.
====

// Interjectiones {{{1
== Interjectiones

[[par107,§107]]§107, Quam interjectiones on posse usar omni interjectiones del national
lingues, queles es comprensibil per se self o es internationalmen
conosset.

====
Halló! Holá! Hé! Huzza! Hurrá! Yuhé! Huhú! Hu, Hu! Ba! Ay! Uf! Via! Nu!
Hopp! Hoppla! Ve! Ho ve! Sus! Psit! Pst! Shut! Sht! Crac! Paf! Plump!
Hm! Hum! Fi!
====

Anc paroles de altri grammatical categories posse esser usat quam
interjectiones: p. ex.

====
Bon! Ad-avan! Retro! For! A-bass! Ad-up! Halt! Auxilie! Adío! Silentie!
Corage! Bravo! Vi! Vive! Mey viver! Salve! Salute!

Huhú! Quant li vent ulula circum li dom! Hu, hu! fanfaron! Holá! veni
che me! Ba! quo to fa, si il ne vole venir! Uf! finit ti desagreabil
labor! Ay! quel dolore! Sus! Sus! al bestie! Subitmen yo audit, que un
person dit pst! detra me. Ma ho ve! il ne atentet e plump! il cadet in
li aqua. Shut (o shit!) vi li professor, silentie! Fi! quel malodore!
====

// Sintax {{{1
== Sintax

[[par108,§108]]§108. Li *position* del paroles in li frase es in general *líber* til un
cert gradu. Ma li *regulari órdine* del frase-partes es:

[width="100%"]
|===
| Subject  | Predicate | Acusativ object | Dativ object

| Li patre | da        | li libre        | al filio
|===

[[par109,§109]]§109. Li frase es maxim bon comprensibil, si omni paroles sta maxim
possibil proxim li parol a quel ili relate. Pro to omni frasepartes es
ínmediatmen sequet o precedet de su atributes.

====
Li bon patre sovente voluntarimen da bell libres a su diligent filio.
====

[[par110,§110]]§110. De to seque, que li *adjective* o atribut adjectivic deve preceder
o sequer ínmediatmen li substantive relativ. In general it precede, si
it es curt o caracteristic, ma seque, si it es long o complementari.

====
Il prefere li delicat fructes del Sud. Ti mann, clar in su pensas e pur
in su intentiones. Su patre e su matre hat fat omni arangeamentes
necessi por su viage. Yo just nu recivet li maxim recent raport
aproximativ pri merces, importat in nor land durante ti estive.
====

[[par111,§111]]§111. Li *adverbies: ne, tre, tro, solmen* e *anc* deve sempre *preceder
ínmediatmen* li parol concernent, che témpores composit ordinarimen li
verb auxiliari; li altri adverbies posse ínmediatmen preceder o sequer
li parol concernent.

====
- Ne *yo* ha prendet vor libre — ma un *altri* person.
- Yo ne *ha* prendet vor libre — ma yo *va* prender it.
- Yo ha ne *prendet* vor libre — ma on ha *dat* it a me.
- Yo ha prendet ne *vor* libre — ma un *aItri*.
- Anc *yo* ama vos. Yo anc *ama* vos. Yo ama anc *vos*.
====

[[par112,§112]]§112. Li *verbes auxiliari* (anc: dever, posser, voler etc.) deve sempre
preceder li participie respectivmen li infinitive ínmediatmen, o esser
separat solmen per concernent adverbies.

====
Nor amícos hat mult laborat, ma ne posset completmen finir lor ovre. Yo
deve aprender ex memorie ti paroles. Yo deve rapidmen aprender ex
memorie ti paroles. Yo strax deve aprender ex memorie ti paroles.
====

[[par113,§113]]§113. Negativ pronómines e adverbies recive li sens positiv solmen si
*ne* sta ínmediatmen avan les. Li talnominat duplic negation es
permisset, ma ne recomendat.

====
Yo videt necos. Yo ne videt necos. Yo videt ne necos, ma solmen tre poc.
====

[[par114,§114]]§114. Anc in li *frases relativ* on usa li *sam órdine* del frase-partes
e li indicative quam in li frases principal. Li subjuntive es usat
solmen in rar casus u li distinction es important, p. ex. in juristic
documentes; in cert casus on posse anc usar li optative.

====
Il di, que il es malad. Il pensat que yo ha venit. On esperat, que il
bentost va venir. Ella questionat, pro quo yo es tam gay. Il di, que il
haye amat la. Yo desira que il mey venir.
====

Por indicar li *condition*, on deve sempre usar: *si*.

====
Si ella vell har savet, quo ella save hodíe, ella vell har actet
altrimen. Si yo vell esser malad, yo vell restar in hem.
====

*Indirect frases* es comensat per: *ca* (viceat sovente per *esque*).

====
Yo ne save, ca yo comprende vos corect. Ca il veni o ne, noi va
comensar. Esque vu savet, ca il va venir? Si on vell saver, ca il veni!
====

Por *vicear relativ frases* on posse multvez usar li infinitive
ínmediatmen pos li verb.

====
Yo crede que yo ha videt le. Yo crede har videt le. Yo crede vider le.
====

[[par115,§115]]§115. Li *acusativ pronómin* seque ínmediatmen li verb; li *dativ
pronómin* precede it ínmediatmen o seque li acusativ pronómin, con o sin
li preposition *a*.

====
Yo videt le. Yo te dat it. Yo dat it te. Yo dat it a te.
====

[[par116,§116]]§116. Li regules indicat por frases direct vale anc por *frases
interrogativ* queles es format per *esque* o altri paroles interrogativ.
Sin li “esque” on posse formar frases interrogativ per posir li subjecte
pos li predicate, resp. pos li verb auxiliari.

====
Esque vu ha comprendet me? Ha vu comprendet me? Quant persones tu crede
vider? Crede tu vider mult persones? Qui tu vide? Qui vide te? Posse vu
audir me? Pensa vu o dormi?
====

[[par117,§117]]§117. Verbes es usat maxim possibil *transitivmen, personalmen* e
*activ*; ma it sempre es permisset usar un sensconform preposition.

====
Yo mersía vos. Ples auxiliar li povri mann. Il menaciat su ínamicos. Yo
memora li cose tre bon. Il prepara un viage. Il prepara se por un viage.
To il solmen imágina. Yo es conscient pri to. Yo senti dolore. Yo
regreta. Yo cale, yo frige. Yo successat far it. On dansat e ludet.
====

Ye li impersonal verbes li pronómin *it* posse esser omisset, si li sens
permisse to.

====
Yo crede que pluvia. Existe mult exceptiones. Pluvia. It pluvia. It
deveni frigid (li temperatura o un cert cose).
====

// Interpunction {{{1
== Interpunction

[[par118,§118]]§118. Li signes de interpunction deve esser usat talmen, que li
comprension del textu es afacilat. Proque lor usation in li lingues
national es multvez contradictori, on deve usar les secun li *principie
natural*, to es por indicar, u on deve stoppar in li leida, respectivmen
por separar li partes del frase.

[[par119,§119]]§119. Li *punctu* (*.*) indica un stoppa passabilmen grand. It es usat
por separar complet frases, expressent un pensa terminat.

[[par120,§120]]§120. Li *punctu-comma* (*;*) indica un stoppa min grand. It es usat por
separar complet frases con pensas coherent.

====
Por hodíe il es content; nam noi laborat del matin til li vésper.
====

[[par121,§121]]§121. Li *comma* (*,*) indica li minim grand stoppa. It es usat por
separar li divers partes de un frase composit, o divers frases coherent
tam mult, que on ne vole separar les per un punctu o punctu-comma.

====
Por hodíe il es content, ma certmen deman noi va dever continuar li
labor, si li tempe va permisser to.
====

Per li comma it es in mult casus possibil far plu clar li sens de un
frase, per indicar, ca li paroles es a separar in un cert loc o in un
altri, o ne es a separar. Specialmen on deve atenter, que atributes,
queles es necessi por definir un cert notion, es adjuntet sin comma,
tales queles descripte solmen, es separat per comma.

====
- Il ha racontat me to quo li altris ne deve saver.
- Il ha racontat me to, quo li altris ne deve saver (que il ha
  racontat it a me).
- Il ne ama li infantes queles fa brui si ili ne es controlat.
- Il ne ama li infantes, queles fa brui si ili ne es controlat.
- Il ne ama li infantes queles fa brui, si ili ne es controlat.
- Il ne ama li infantes, queles fa brui, si ili ne es controlat.
====

[[par122,§122]]§122. Por indicar li paroles maxim important del frase on posse usar li
*accentu scrit*.

====
Yó ea con la (ne tú). Yo éa con la (yo ne fa quam li altris, queles né
ea con la). Yo ea con élla (ne con li áltris). Save vu, de u il veni?
====

[[par123,§123]]§123. Li *altri signes de interpunction*:

Colon (:), punctus suspensiv (...), parentese ({nbsp}), crampones ([{nbsp}]),
imbrassamentes({ }), strec ligant (-), strec separant (—), signes
(hocos) de citation ("{nbsp}"), signe de exclamation (!), signe interrogativ
(?) e apostrof (') es usat plu o min internationalmen. (! e ? sta solmen
in li fine del frase, ne anc in li comensa.)

// Parolformation {{{1
== Parolformation

[[par124,§124]]§124. *Nov paroles* es format per:

- <<_adjuntion_de_desinenties, Adjuntion de desinenties>>.
- <<_adjuntion_de_prefixes, Adjuntion de prefixes>>.
- <<_adjuntion_de_sufixes, Adjuntion de sufixes>>.
- <<_composition_de_du_o_pluri_paroles, Composition de du o pluri
  paroles>>.

// Adjuntion de desinenties {{{2
=== Adjuntion de desinenties

[[par125,§125]]§125. Li adjuntion de desinenties es ja tractat in li concernent
paragrafes del grammatica:

1. Desinenties substantivic:
* *-e* (<<par22>>, <<par30>>, <<par87>>).
* *-a* (<<par24>>, <<par30>>, <<par87>>).
* *-o* (<<par24>>, <<par30>>).
* *-u* (<<par25>>).
* *-um* (<<par31>>).
2. Desinentie adjectivic:
* *-i* (<<par29>>).
3. Desinenties adverbial:
* *-e* (<<par74>>).
* *-men* (<<par90>>).

[[par126,§126]]§126. Ti desinenties es un consequentie del *caracterisant vocales
final* de Interlingue:

*-e* es li finale general, sin special signification, usat por fixar li
corect pronunciation del precedent consonant, pro eufonie o distinction
de simil paroles (precipue de substantives del egalform adjective).

====
pace, image, rose, libre, cable, altruisme, curve, centre, central,
centrale, directiv, directive, marine, circulare, cantate, infinite,
tangente, adherente, manjante, denove.
====

*-a* trova se in paroles indicant activitá, loc o témpor de it, alquó
extendet, universal, colectiv, con vivent entes lu feminin.

====
dansa, dansada, plazza, imperia, era, pasca, rosiera, liga, secta,
posta, americana, filia, studianta, cavalla.
====

*-o* trova se in paroles indicant lu concret, material, special,
individual, con vivent entes lu masculin.

====
forso, humo, rosiero, posto, americano, filio, cavallo.
====

*-u* indica alquó abstract, neutri, un relativitá, o es usat por reciver
li international derivates.

====
statu, casu, unaltru, manu, gradu.
====

*-i* es li finale adjectivic, por fixar li corect pronunciation del
consonant final, pro eufonie o por distinction de simil paroles.

====
felici, sagi, porosi, organisatori, amari, curvi, vacui.
====

e, a, o, u, i:

====
rose, rosi, rosiero, rosiera; porte, porta, portu,
portuari, portale; posta, posto.
====

// Adjuntion de prefixes {{{2
=== Adjuntion de prefixes

// XXX FIXED -- prefixial -> prefixal

[[par127,§127]]§127. In mult international parolformationes li prefixes e prefixal
expressiones perdi su ultim consonant o assimila it al sequent
consonant; in ti casu duplic consonantes es viceat secun <<par10>> per
simplics, exceptet pos ín- (ma anc li altri ortografies es permisset).

====
- adtracter — attracter — atracter
- conlaborar — collaborar — colaborar,
- conoperativ — cooperativ
- conposition — composition
- disfuser — diffuser, difuser
- exmigrar — emmigrar — emigrar
- coneducation — coeducation
- ínregulari — irregulari
- ínlegal — illegal.
====

[[par128,§128]]§128. Li *prefixes* es:

bel-:: Parentitá per maritage: *belfratre, belfilio*.

des-:: Cessation, contrarie: *desabonnar, desinfecter, desavantage*.

dis-:: Separation, dispersion: *dismembrar, dissemar*.

ex-:: Ancian: *expresidente, eximperator*.

ho-:: Sam témpor: *hodíe, hosemane, hoannu*.

ín-:: Negation in adjectives: *ínoficial, ínvisibil* (ne a confuser al
inaccentuat preposition: in-: inpaccar).

mi-:: Curt form de demí: *midí, minocte, mihor, mifratre*.

mis-:: Fals, ínconvenient, fallient: *miscomprender, misalliantie,
misdirecter*.

non-:: Negation in substantives: *nonsens, nonfumator*.

per-:: Tra, til fine: *perforar, percurrer*.

pre-:: In ante, avan: *previder, preparar, prehistorie, presider*.

pro-:: Ad avan, ad extra: *progression, producter*.

re-:: Denove, ad comensa: *revider, revenir*.

step-:: Parentitá per un duesim maritage: *stepmatre, stepfilio*.

[[par129,§129]]§129. Quam prefixes on usa anc *prepositiones, adverbies e li presente*
de quelc verbes:

====
adaptar, abreviar, atirar, antedatar, avanbrass, circumscription,
consentir, coeducation, coroder, compresser, contrasignar, depender,
excluder, expectar, extraordinari, forear, infiltrar, iluminar,
importar, intervenir, preterpassar, retromarchar, retroactiv,
selfconfidentie, submisser, transportar, transpirar, tradition,
ultraclerical, vicepresidente, parapluvie, portamoné, tirabuton.
====

[[par130,§130]]§130. Mult international paroles es format per *grec prefixes*:

====
decametre, decilitre, hectolitre, hemisfere, hipermodern, kilometre,
monoplan, panslavisme, pseudocrist, telefonar.
====

// Adjuntion de sufixes {{{2
=== Adjuntion de sufixes

[[par131,§131]]§131. Li sufixes adjunte se al radica ínmediatmen o med vocales o
consonantes ligativ. In infra es indicat li complet finales, ma sin
alquel desinenties facultativ.

On posse adjunter pluri sufixes in li sam parol.

[[par132,§132]]§132. In mult international parolformationes existe un *contraction* de
du simil succedent sones o songruppes a un sol. P. ex.:

====
minera(lo)logie, popular(i)isar, pacif(ic)isme,
infanter(i)ist, ambiti(on)osi, religi(on)osi, ident(ic)itá,
nu(tri)tresse, mum(i)ificar.
====

// Taxant sufixes {{{3
==== Taxant sufixes

[[par133,§133]]§133.

-ett:: Diminutive, frequentative, micri objectes: *filietto, statuette,
cigarrette, pincette, inflammette, rosette, foliettar, volettar,
saltettar*.

-illio, -innia:: Caressiv: *fratrillio, matrinnia, carinnia*.

-issim:: In maxim alt gradu: *grandissim, bellissim*.

-ach:: Pejorativ, despreciant: *cavallacho, linguache, criticachar*.

// Verbal sufixes {{{3
==== Verbal sufixes

[[par134,§134]]§134. *Finale -ar*. Omni modern formationes de verbes fini per -ar, ne
per -ir e ne per -er. Li maxim mult verbes es derivat de altri paroles
per li *ínmediat derivation*, to es per adjunter li finale del
infinitive *-ar*, sin sufix.

Ti verbes derivat have divers significationes:

1. De objectes, materiales, abstractes: provider per: *coronar, armar,
   motivar*.
2. De utensiles, instrumentes: usar, tractar per: *brossar,
   martellar*.
3. De organic productes: secreer it: *lactar, ovar, sanguar*.
4. De persones e entes: acter quam: *dominar, serpentar*.
5. De adjectives e participies (sovente con prepositiones): far tal:
   *plenar, siccar, exsiccar, abellar, calentar, sedentar*.

In mult casus existe altri relationes internationalmen conosset: *beson,
besonar, cure, curar, risca, riscar, don, donar, matur, maturar*.

[[par135,§135]]§135. *Altri verbal finales*.

-isar:: Far tal, far quam: *electrisar, idealisar, canalisar,
terrorisar, rivalisar, judeisar*.

-ificar:: Far tal, constatar quam: *verificar, simplificar, mumificar,
pacificar*. forma anc adjectives: *pacific, magnific, specific*.

-ijar:: Devenir, far se: *verdijar, rubijar*.

-ear:: Statu dinamic de vade e retro: *flammear, verdear, undear*.

// XXX FIXED -- "statú" -> "statu"
// XXX FIXED -- "interiori" -> "inferiori"
// XXX FIXED -- "pseudomala-die" -> pseudomaladie"

// Sufixes por verbal substantives {{{3
==== Sufixes por verbal substantives

[[par136,§136]]§136.

a) adjuntet al *tema perfectic* secun <<par80>>:

-ion:: Action, anc resultat e loc de it: *administration, expedition,
construction, distribution, explosion*.

[[_or]]-or:: Actent person, cose o factor: *administrator, expeditor,
distributor, constructor, ventilator, compressor, divisor*.

-ura:: Concretisat action e su resultate: *reparatura, garnitura,
lectura, creatura*.

b) adjuntet al *tema presentic* secun <<par84>>:

-ment:: Concret action o su resultate, o servient a, servient quam:
*fundament, nutriment, movement*.

c) adjuntet al *radica verbal* secun <<par85>>:

-ida (verbes in *-ar*: *-ada*):: Action in durada: *promenada, perdida,
currida*.

d) adjuntet al *participie presentic* secun <<par82>>:

-ie:: Statu in durada: *tolerantie, provenientie, existentie*.

// Personal sufixes {{{3
==== Personal sufixes

[[par137,§137]]§137.

-er-:: Person professional: *molinero, lavera, librero, vitrero*.

-ist:: Person ocupant se pri, adherente de: *calvinist, socialist,
librist, telegrafista*.

-or:: cp. <<par136>>.

-ari-:: Person caracterisat per alquó external, p. ex. un function:
*millionario, functionaria, bibliotecario, pensionaria*.

-on:: Person caracterisat per un intern o natural qualitá: *dormon,
savagion, spiona, pedon*.

-ard:: Persones con mal qualitá: *falsard, dinamitard, mentard*.

-astr-:: Persones de valore inferiori: *medicastro, poetastra*.

-es-:: Habitante (anc adjectivic): *francese, franceso, francesa,
francesi, borgeso*. *-ane, -ano, -ana*: cp. <<par140>>.

-essa:: Féminas con special dignitá o function: *princessa, diaconessa,
actressa, imperatressa*.

-ell:: Yun animale: *agnell, leonello*.

// Qualitativ sufixes {{{3
==== Qualitativ sufixes

[[par138,§138]]§138.

-ie:: Abstract substantives, statu (cp. <<par82>>, <<par136>>): *anatomie, maladie,
elegantie, existentie, furie, tirannie*.

-itá (*-etá*, si li radica fini per *i*):: Qualitá: *homanitá, yunitá,
quantitá, proprietá, ebrietá*.

-ore:: De verbes: statu; de adjectives: qualitá mesurabil: *amore,
terrore, calore, longore, grandore*.

-esse:: Pregnant qualitá o statu: *altesse, grandesse, finesse,
yunesse, delicatesse*.

// Local e colectiv sufixes {{{3
==== Local e colectiv sufixes

[[par139,§139]]§139.

-ia:: Loc, land: *dormitoria, Germania, dominia, abatia*.

-eríe:: Profession e su productes (*-er* + *-ie*), metaforicmen anc maniere
de acter, caractere: *vitreríe, potteríe, bigotteríe, diaboleríe*.

-ería:: Loc de profession (*-er* + *-ia*): *librería, juvelería, vitrería*.

-iera:: Vast loc contenent alquo: *torfiera, pisciera, rosiera*.

-iere:: Vase etc., contenent alquo: *incriere, tabaciere, butoniere*.

-iero:: Portant alquo: *rosiero, candeliero, pomiero*.

-atu:: Institution o situation social o legal, dignitá, anc loc, témpor
o dominia de it: *viduatu, proletariatu, secretariatu, califatu,
episcopatu*.

-uore:: Loc, utensil: *trottuore, lavuore, reservuore, tiruore*.

-ade:: Multitá, serie, contenida: *colonade, boccade, olimpiade*.

-allia:: Colectives sin órdine, o despreciativ: *antiquallia,
ferrallia, canallia*.

-age:: Colectives con órdine, coses fat de: *foliage, plumage, boscage,
tonnage, plantage, lanage, linage*.
De verbes: activitá, precipue industrial o professional, anc su
resultate, loc o témpor, anc li custas por it: *rafinage, abordage,
luage, viage, doanage*.

-arium:: Colection ordinat, precipue scientic o tecnic: *herbarium,
planetarium, aquarium, rosarium*.

-ité (*-eté*, si li radica fini per *i*):: Totalité de persones o coses:
*homanité, yunité, societé*.

-un:: Singul exemplare: *grelun, sablun, scalun*.

// Adjectivic sufixes {{{3
==== Adjectivic sufixes

[[par140,§140]]§140.

(Li concernent substantives, format per desinenties substantivic, es
indicat in parenteses.)

-al:: General adjectivic relation: *musical, cordial, central
(centrale), ideal (ideale)*.

-ic:: Essent tal: *metallic, fanatic (fanatico), fantastic, scientic*.
+
Grec substantives finient per *-ma* intercala *-t-*, tales finient per
*-se* (x = cs) muta li *s* in *t: problematic, dramatic, elipse,
eliptic, hipnose, hipnotic, sintax, sintactic (sintactico)*.
+
Per *-ica* on indica scienties o artes, per *-ico* lor executores:
*fisic, fisica, fisico, aviatica, aviatico, politic, politica,
politico*.

-an:: Apartenent a: *american (americano, americana, americanes),
homan*.

-at (pos substantives):: Providet per: *barbat, foliat, talentat
(talentate)*.

-ut:: Tro rich in, exuberant: *barbut (barbute), armut, sandut*.

-osi:: Rich in, havent: *famosi, musculosi, respectosi, spinosi*.

-aci:: Inclinat a: *mordaci, tenaci, vivaci*.

-ari:: Conform a, convenient a: *populari, regulari, militari
(militare)*.

-atri:: Simil a: *spongiatri, verdatri*.

-esc:: Amemorant a, in maniere de: *infantesc (infantesco), gigantesc*.

-in:: Consistent de, provenient de: *argentin, alpin, matrin, svinin
(svinine)*.

-iv::
Adjuntet al tema perfectic secun <<par80>>. Actent talmen, capabil:
*decorativ, obligativ, consolativ, definitiv, constructiv, ofensiv
(ofensive), directiv (directive), alternativ (alternative)*.

-ori::
Adjuntet al tema perfectic secun <<par80>>. Destinat a, devent
acter talmen (adjective de <<_or,*-or*>>): *decoratori, obligatori, consolatori,
ilusori, preparatori, instructori*.

-ibil::
Verbes in *-ar*: *-abil*, cp. <<par85>>. De verbes transitiv: quo on
posse far; de verbes íntransitiv: quo posse far: *formabil, audibil,
íncredibil, visibil, explosibil, combustibil (combustibile)*.

-nd::
Verbes in *-ir*: *-end*. Adjuntet al tema presentic. A far: *leend,
dividend (dividende)*.

[[par141,§141]]§141. Mult paroles international contene *grec e latin afixes*:

ab-:: For: *abducter*.

anti-:: Contra: *anticrist, antisocial*.

arch(i)-:: Gradu maxim superiori: *archangel, archiepiscop,
archifripon*.

auto-:: Self: *automobile, autodidacte*.

pseudo-:: Fals, semblant: *pseudoscientie, pseudocrist,
pseudomaladie*.

-isme:: Doctrin, sistema, movement: *catolicisme, centralisme,
socialisme*.

-oid:: Simil: *negroid (negroide), elipsoid*.

[[par142,§142]]§142. Ultra li indicat *productiv afixes* existe quelc *ínproductiv
afixes*, queles ne forma nov paroles, ma explica existent paroles
international. P. ex.: *-id, -ore*.

====
friger, frigid, frigore, valer, valid, valore, riger, rigid, rigore,
rigiditá, rigorosí, rigorositá.
====

// Composition de du o pluri paroles {{{2
=== Composition de du o pluri paroles

[[par143,§143]]§143. Maxim frequent es li metode plazzar li complement sin preposition
avan li substantive resp. li verb, con o sin strec ligativ.

====
scri-table (={nbsp}table por scrir), vent-moline (={nbsp}moline movet
del vent), chapel-bux, nota-librette, postcarte, scrimachine,
tippmachine, mult-lateral, circumnavigar,contraproposition.
====

In nov-formationes it es recomendat ligar li du paroles per un strec
ligativ. In compositiones ja international li du paroles multvez es
ligat per un *o* o *i*.

// XXX FIXED -- uníform -> uniform

====
ferrovia, agricultura, uniform, li uniforme, aeroplan, electromotor.
====

Pro simplicitá e plu grand comprensibilitá e claritá it recomenda se in
mult casus usar atributes vice compositiones.

====
animale domestic, premie de assecurantie, comunication per vapornaves.
====

// Frases sistematic por omni essential regules grammatical {{{1
== Frases sistematic por omni essential regules grammatical

Li sequent unic págine de frases in Interlingue contene por chascun
essential regul del grammatica de Interlingue, inclusive li sintax, un
frase specimenic. Tam simplic es li mecanisme de ti lingue
international, que un mult plu grand circul de persones es capabil
realmen mastrisar ti simplic mecanisme sin exceptiones, quam to vell
esser possibil in alquel lingue national con su mult plu complicat
regules e con omni li exceptiones e li amasse de special manieres de
expression. Tamen Interlingue possede li plen expressivitá del lingues
national; nam it ne renuncia a cert possibilitás de expression, it
solmen selecte in chascun punctu li maxim simplic o li maxim conosset
form de expression.

1. Yo manja un pom. Li pom es un fructe. Tu manja un pir. It anc es un
fructe. Noi manja du bon fructes. Mi fratre manja prunes; il manja tri
prunes. Mi sestra manja cereses; ella manja mult cereses. lli manja
prunes e cereses. Vu manja pires, prunes e cereses. On manja li mult bon
fructes. Yo prefere li dulcis. A mi patre yo di “tu”, ma tu di “vu” a mi
patre. Li patre es grand e li matre anc es grand; ili es grand.

2. Yo vide te. Yo da te un pir. Yo da li pir a te. Li pir es de me. Li
patre da un pom al filia. Ella es li sestra del filio.

3. Yo lava me. Yo lava te. Tu lava me. Tu lava te. Tu lava le. Il lava
se. Il lava le. Il lava la. Il lava it. Il lava nos. Ella lava se. It
lava se. It lava it. On lava se. Noi lava nos. Vu lava vos. Vu lava nos.
lli lava se. lli lava les. Yo da mi pom a te. Tu da tui pir a nos. Vu da
vor fructes a les. lli da lor fructes a le. Yo da te mi pom, etc.

4. Mi pom es plu grand quam su prunes, ma it es min grand quam tui pir.
Li maxim grand de vor fructes es tui pir, li minim grand su cereses. Nor
pom e pir es tam bell quam lor prunes e cereses. Nor fructes es tam bell
quam li lores. Lu maxim bell es li bellissim composition del colores.

5. Yo es ci. Tu anc es ci. Ma il es ta, Ti fructes es bell. Ti-ci pom
es verd. Ma ti-ta pir es yelb. Ti-ci cereses es rubi, tis-ta es nigri.
To es bell colores.

6. Qui veni? Li filia. Quel filia? Li filia del vicino. Qual es li dom
del vicino? Su dom es grand. Quo li filia vole? Ella aporta fructes por
li infantes queles ama les. Yo ne save quo far, nam omnes ama les. Tis
qui ha laborat maxim mult, recive li maxim grand fructes; tis queles ha
laborat poc, recive li min grand fructes. Talmen on save tre rapidmen
qualmen distribuer li fructes. Ti metode functiona bon; it es corect.

7. Hodíe yo labora ci. Yer yo ha arivat. Yo arivat per li tren de
Paris, u yo hat laborat antey. Deman yo va departer per auto pos har
finit mi labor. Yo vell restar plu long, ma on telegrafat me: Veni tam
bentost quam possibil! Dunc lass nos finir nor maxim urgent labores. Li
altri labores queles yo ancor vell har devet far, yo va dever far plu
tard; ples excusar to. Quande yo fa bon mi labores, yo es estimat e yo
va esser bon payat. In Paris yo hat esset honorat per un special premie.
To mey suficer.

8. Li patre da li libre al filio. Li bon patre sovente voluntarimen da
bell libres a su diligent filio. Il da ne li fructe, ma li libre. Ne il
da li libre, ma ella. Anc yo ama vos. Yo ama solmen vos. Yo videt le. Yo
te dat it. Yo dat it te. Yo dat it a te. A te yo dat it.

9. Esque vu hat comprendet me? Ha vu comprendet me? Quant persones tu
crede vider? Crede tu vider mult persones? Qui tu vide? Qui vide te? Il
di que il es malad. Il pensat que yo ha venit. Ella questionat, proquo
yo es tam gay. Yo desira que il mey venir. Si yo vell esser malad, yo
vell restar in hem. Yo ne save, ca yo comprende vos corect. Ca il veni o
ne, noi va comensar, Si on vell saver, ca il veni! Yo crede que yo ha
videt le. Yo crede har videt le. Yo crede vider le.

// XXX TODO -- Use uppercase instead?:

Accentuati**o**n: Li p**o**c art**i**cules del gramm**a**tica e li
vocabul**a**rium de Interl**i**ngue es facil**i**ssim e repres**e**nta
**í**ndubit**a**bilmen li m**a**ximum de simplicit**á**.

// XXX FIXED -- "Ll lingue" -> "Li lingue"

// Li lingue vermen international {{{1
== Li lingue vermen international

Textu de un disco de grammofon recivibil del Interlingue-Centrale:

____

Car auditores!

St. Gallen 7, Svissia.

Yo parla a vos in li lingue international Interlingue. Li centre del
international Interlingue-Union ha fat li edition de ti disco de
grammofon por demonstrar a omni interessates, que Interlingue ne sona
quam un lingue artificial e constructet, ma quam un lingue tot natural e
simil al lingues national. E si vu studia un textu in Interlingue, vu va
constatar, que anc printat e scrit, li aspecte de ti lingue es egal a ti
del grand lingues cultural del occidente con scrition per lítteres
latin. Ti lítteres latin es usat in li maniere ja acustomat al maxim
grand númere de europanes e americanes, e li unitari pronunciation es
garantit, proque omnes have ja nu li ocasion acustomar se al normal
pronunciation per li medie del discos de grammofon. E certmen pos un
curt témpor on va anc in li radio-emissiones sempre plu e plu audir
discurses e novas parlat in li lingue international Interlingue.

Si noi parla a un person pri Interlingue, on questiona nos sempre: Ma it
existe ya ja altri lingues, queles nómina se mundlingue. Yes, on fat un
grand reclame por ti lingues, e mult homes con imens entusiasme ha
sacrificat durante plu quam sixant annus mult labor e enorm summas por
li ideale de un lingue comun por omni popules del terra. Ma
regretabilmen omni ti penas ne posset haver success, proque li munde ne
accepta un lingue artificial, un lingue quel fa necessi reflecter in un
maniere contrari al acustomation de omni nationes. Pro to on devet in
prim trovar un lingue, quel contene li vermen international paroles, ma
in lor formes natural, ne deformat per artificialmen adjuntet vocales e
consonantes e síllabes. E anc li grammatica deve esser tam simplic quam
possibil. It ne deve contener regules complicat, queles mem ne existe in
li majorité del lingues national, quo pruva, que ti regules ne es
necessi por li clar expression e comprension del pensas.

Ti defectes on conosset ja ante annus. Ma on credet esser obligat al
adherentes e al editores del libres, e ne plu posset introducter li
desirat corecturas in li lingue. Pro to on proclamat, ne plu far li
minim change durant un periode de stabilitá, o ante li oficial adoption
per pluri guvernamentes. Ma certmen vu omnes es convictet con me, que it
es un erra, dir, que on va changear li lingue, quande li munde ha
acceptat e aprendet it. No, in contrarie, li munde ne va acceptar e
aprender li lingue international, ante que it es corectet e ha trovat su
form definitiv e final.

Pro to Edgar de Wahl, professor in Tallinn, Estonia, separat se del
lingue-projectes artificial e serchat li solution del problema in un
altri direction. Il studiat denov li lingues national self, e serchat li
paroles e li regules grammatical ja existent in li maxim mult lingues
cultural. Per li decovrition del talnominat “Regul de Wahl” il
regularisat milles de extrem frequent paroles, queles li precedent
projectes de lingue international devet excluder e vicear per artificial
parol-constructiones. Ti Regul de Wahl es li miraculosi clave al sol
lingue vermen international e in sam témpor regulari. Edgar de Wahl ha
studiat scienties exact, linguistica e bell artes. Fórsan just ti
mixtura de interesses e saventies fat possibil, que il trovat un lingue
ínataccabil del vispunctu scientic, e in sam témpor ne desagreabil por
li lingual sentiment. Interlingue es un lingue autonom e harmonic, e
contene omni essentiai elementes del principal lingues de Europa e
America. It es mult plu facil quam li precedent projectes de lingue
international e íncomparabilmen plu simplic quam omni lingues national.
Un lettre scrit in Interlingue es ja hodíe comprendet de omni persones
del munde con relationes international. E proque nequí va serchar
paroles plu international quam li paroles international self, nequí va
far un proposition por un nov projecte de lingue international, pos li
seriosi studie de Interlingue li sol lingue vermen international.
____
